environment:
  name: "CarRacing-v3"
  render_mode: "rgb_array"   # "human" to watch live
  n_episodes: 3000
  log_interval: 10
  mode: "dqn"                # discrete | continuous | dqn

discrete:
  algorithm: "double_q_learning"
  policy: "epsilon_greedy"
  hyperparameters:
    learning_rate: 0.05
    discount_factor: 0.95
    epsilon: 1.0
    exploration_decay: 0.998
    final_epsilon: 0.05
    temperature: 1.5

continuous:
  algorithm: "double_q_learning"
  policy: "epsilon_greedy"
  action_set: "smooth"
  hyperparameters:
    learning_rate: 0.05
    discount_factor: 0.95
    epsilon: 1.0
    exploration_decay: 0.998
    final_epsilon: 0.05
    temperature: 1.5

dqn:
  algorithm: "double_dqn"    # dqn | double_dqn
  use_continuous: true
  action_set: "smooth"       # only used if use_continuous: true
  hyperparameters:
    learning_rate: 0.0001
    discount_factor: 0.99
    epsilon: 1.0
    exploration_decay: 0.9990
    final_epsilon: 0.05
    batch_size: 32
    replay_buffer_size: 50000
    target_update_freq: 1000
    train_start: 10000

observation:
  method: "feature"
  n_bins: 6
  n_regions: 6

save_path: "agent_weights"